### ISSUE TITLE
Missing dependencies on "bart" docker image

### ISSUE THREAD

**Issue by pfuchs** [mrphysics-bonn/python-ismrmrd-reco#3]
When building the server using ./build_server (in this case with the MKL lines commented out, though I don't think that is relevant for the given errors) and trying a reconstruction with ./send_files the following errors appear in the logfile:

```python
2024-02-23 13:22:04,949 - No module named 'dipy'
Traceback (most recent call last):
  File "/opt/code/python-ismrmrd-server/server.py", line 104, in handle
    import bart_pulseq
  File "/opt/code/python-ismrmrd-server/bart_pulseq.py", line 7, in <module>
    import bart_pulseq_spiral
  File "/opt/code/python-ismrmrd-server/bart_pulseq_spiral.py", line 10, in <module>
    from pulseq_helper import insert_hdr, insert_acq, get_ismrmrd_arrays, read_acqs
  File "/opt/code/python-ismrmrd-server/pulseq_helper.py", line 11, in <module>
    from reco_helper import calc_rotmat, gcs_to_dcs, dcs_to_gcs, intp_axis
  File "/opt/code/python-ismrmrd-server/reco_helper.py", line 12, in <module>
    from dipy.segment.mask import median_otsu
ModuleNotFoundError: No module named 'dipy'
```

followed by an identical error for ```despike``` and ```psutil```, all three of which are solved by adding these packages to the pip3 call in line 110 of the Dockerfile.

Not sure why these dependencies seem to be missing when I build the server, perhaps some of the recon scripts have changed to include these without updating the Docker image, or I should be using a different image from the "bart" image (I saw that psutil is included in bart_pg_cpu for example).

**Comment by mavel101** [comment]
Thank you for posting this issue. We included the missing packages in the Dockerfiles in the latest commit.
